d/t/test-autotest: bump sse feature check
Since https://git.dpdk.org/dpdk/commit/?id=f27769f796a (=DPDK 17.08)
the minimum is actually sse4_2.

If sse3 is present but sse4_2 missing you'll get:
   $ testpmd ...
   ERROR: This system does not support "SSE4_2".
   Please check that RTE_MACHINE is set correctly.
   EAL: FATAL: unsupported cpu type.
   EAL: unsupported cpu type.

FYI: I've updated the Ubuntu docs [1], consider the same for Debian if there
is anything to update.

[1]: https://ubuntu.com/server/docs/network-dpdk

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>

diff --git a/debian/tests/test-autotest b/debian/tests/test-autotest
--- a/debian/tests/test-autotest
+++ b/debian/tests/test-autotest
@@ -10,8 +10,8 @@ ARCH=$(dpkg --print-architecture)
 echo "Check required features on arch: ${ARCH}"
 case "${ARCH}" in
     amd64)
-        if ! grep -q '^flags.*sse3' /proc/cpuinfo; then
-            echo "Missing sse3 on ${ARCH} - not supported, SKIP test"
+        if ! grep -q '^flags.*sse4_2' /proc/cpuinfo; then
+            echo "Missing sse4_2 on ${ARCH} - not supported, SKIP test"
             exit 77
         fi
         ;;
